controller_list:
  # Controller for executing joint-space trajectories on a group of joints  on the "Gazebo Robot" & the "Physical Robot"
  - name: Maulesh/phantomx_arm/arm_controller
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4 
  - name: Maulesh/phantomx_arm/gripper_controller
    type: GripperCommand
    action_ns: gripper_action
    default: true
    joints:
      - joint_5
